# Generated by Django 5.2.15 on 2026-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('posicao', models.CharField(max_length=100)),
                ('nascimento', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='integrantes/')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('historia', models.TextField()),
                ('autores', models.CharField(max_length=200)),
                ('copyright', models.CharField(max_length=100)),
            ],
        ),
    ]
